### ISSUE TITLE
Sublevel sets visualization

### ISSUE THREAD

**Issue by XYZhang163** [IsolationKernel/Codes#3]
Hi, I am very interested in lambda-kernel and its application in persistent homology!

Would you consider share how to visualize the sublevel sets of different filter functions, like table5 in appendix?

**Comment by CaptainJuice** [comment]
Glad you like it ! The sublevel set visualizatio of different filters is uploaded now. See at [https://github.com/IsolationKernel/Codes/blob/main/Lambda-kernel/sublevel_set.ipynb](url)
